apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: mysql
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS app_db;
    CREATE USER IF NOT EXISTS 'app_user'@'%' IDENTIFIED BY 'app_password';
    GRANT ALL PRIVILEGES ON app_db.* TO 'app_user'@'%';
    USE app_db;
    CREATE TABLE IF NOT EXISTS counter (
        id INT AUTO_INCREMENT PRIMARY KEY,
        value INT
    );
